local _NAME = ...
  
local lc = require ( _NAME .. "/layoutcreator" )()
lc:registerLayout("linear", require( _NAME .. "/layout/linear" )(lc))
lc:registerLayout("text", require( _NAME .. "/layout/text" )(lc))
lc:registerLayout("image", require( _NAME .. "/layout/image" )(lc))
lc:registerLayout("caption", require( _NAME .. "/layout/caption" )(lc))
lc:registerLayout("list", require( _NAME .. "/layout/list" )(lc))
lc:registerLayout("root", require( _NAME .. "/layout/root" )(lc))
lc:registerLayout("stack", require( _NAME .. "/layout/stack" )(lc))
lc:registerLayout("freeform", require( _NAME .. "/layout/freeform" )(lc))
lc:registerLayout("stackroot", require( _NAME .. "/layout/stackroot" )(lc))
lc:registerLayout("dragbox", require( _NAME .. "/layout/dragbox" )(lc))
lc:registerLayout("numberasimage", require( _NAME .. "/layout/numberasimage" )(lc))
lc:registerLayout("empty", require( _NAME .. "/layout/empty" )(lc))
lc:registerLayout("filler", require( _NAME .. "/layout/filler" )(lc))
lc:registerLayout("4pane", require( _NAME .. "/layout/4pane" =)(lc))
lc:registerLayout("aquarium", require( _NAME .. "/layout/aquarium" =)(lc))

lc:registerStyledLayout("filler.right", "filler", { right = "fill" })
lc:registerStyledLayout("filler.left", "filler", { left = "fill" })
lc:registerStyledLayout("filler.top", "filler", { top = "fill" })
lc:registerStyledLayout("filler.bottom", "filler", { bottom = "fill" })
lc:registerStyledLayout("filler.topright", "filler", { top = "fill", right = "fill" })
lc:registerStyledLayout("filler.topleft", "filler", { top = "fill", left = "fill" })
lc:registerStyledLayout("filler.bottomright", "filler", { bottom = "fill", right = "fill" })
lc:registerStyledLayout("filler.bottomleft", "filler", { bottom = "fill", left = "fill" })
lc:registerStyledLayout("filler.center", "filler", { top = "fill", bottom = "fill", left = "fill", right = "fill" })

return lc