local _NAME = ...
  
local looky = require ( _NAME .. "/layoutcreator" )()
looky:registerLayout("linear", require( _NAME .. "/layout/linear" )(looky))
looky:registerLayout("text", require( _NAME .. "/layout/text" )(looky))
looky:registerLayout("image", require( _NAME .. "/layout/image" )(looky))
looky:registerLayout("list", require( _NAME .. "/layout/list" )(looky))
looky:registerLayout("root", require( _NAME .. "/layout/root" )(looky))
looky:registerLayout("stack", require( _NAME .. "/layout/stack" )(looky))
looky:registerLayout("freeform", require( _NAME .. "/layout/freeform" )(looky))
looky:registerLayout("stackroot", require( _NAME .. "/layout/stackroot" )(looky))
looky:registerLayout("dragbox", require( _NAME .. "/layout/dragbox" )(looky))
looky:registerLayout("numberasimage", require( _NAME .. "/layout/numberasimage" )(looky))
looky:registerLayout("numberasbar", require( _NAME .. "/layout/numberasbar" )(looky))
looky:registerLayout("empty", require( _NAME .. "/layout/empty" )(looky))
looky:registerLayout("filler", require( _NAME .. "/layout/filler" )(looky))
looky:registerLayout("4pane", require( _NAME .. "/layout/4pane" )(looky))
looky:registerLayout("aquarium", require( _NAME .. "/layout/aquarium" )(looky))
looky:registerLayout("slotted", require( _NAME .. "/layout/slotted" )(looky))

looky:registerStyledLayout("filler.right", "filler", { right = "fill" })
looky:registerStyledLayout("filler.left", "filler", { left = "fill" })
looky:registerStyledLayout("filler.top", "filler", { top = "fill" })
looky:registerStyledLayout("filler.bottom", "filler", { bottom = "fill" })
looky:registerStyledLayout("filler.topright", "filler", { top = "fill", right = "fill" })
looky:registerStyledLayout("filler.topleft", "filler", { top = "fill", left = "fill" })
looky:registerStyledLayout("filler.bottomright", "filler", { bottom = "fill", right = "fill" })
looky:registerStyledLayout("filler.bottomleft", "filler", { bottom = "fill", left = "fill" })
looky:registerStyledLayout("filler.center", "filler", { top = "fill", bottom = "fill", left = "fill", right = "fill" })

return looky